pipeline:
  name: Node.js Build
  identifier: nodejs_build
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: gitconnect
        repoName: reactcalculator
        build: <+input>
  stages:
    - stage:
        name: Build
        identifier: build
        type: CI
        spec:
          cloneCodebase: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: harnessImage
              namespace: harness-test
          failureStrategies:
            - onFailure:
                errors:
                  - AllErrors
                action:
                  type: Abort
          execution:
            steps:
              - step:
                  type: Run
                  identifier: build_javascript_app
                  name: Build JavaScript App
                  spec:
                    connectorRef: harnessImage
                    image: node:latest
                    shell: Sh
                    command: |-
                      echo "Welcome to Harness CI"
                      node --version
                      npm install
                      npm run build --if-present
                      npm test
